[phases.setup]
nixPkgs = ["php81", "php81Packages.composer"]

[phases.install]
cmds = ["echo 'PHP setup complete'"]

[phases.build]
cmds = ["echo 'No build step required for WordPress'"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public_html"